# Docker compose file for Jenkins CI/CD
services:
  jenkins:
    build:
      context: ./jenkins/
      dockerfile: Dockerfile
    image: jenkins/jenkins:lts
    ports:
      - '8090:8080'
      - '50000:50000'
    
    environment:
      - JAVA_OPTS=-Duser.timezone=Europe/Madrid
    volumes:
      - /var/opt/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock 
    networks:
      - jenkins_network
    
    restart: unless-stopped
  
  docker-agent:
    depends_on:
      - jenkins
    image: jenkins-agent-docker:0.0.2

    environment:
      - JENKINS_URL=http://jenkins:8080 
      - JENKINS_SECRET=$JENKINS_SECRET
      - JENKINS_AGENT_NAME=docker-container

    volumes:
      - /var/opt/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:rw
    
    privileged: true

    networks:
      - jenkins_network
    restart: unless-stopped

  
networks:
  jenkins_network:
    driver: bridge