# Docker compose file for Jenkins CI/CD
name: jenkins
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - /var/opt/jenkins_home:/var/jenkins_home
    networks:
      - jenkins_network
    restart: unless-stopped
     
  docker:
    image: docker:20.10.7
    container_name: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_network


networks:
  jenkins_network:
    driver: bridge