// Jenkinsfile
pipeline {
    agent any

    stages {
        stage('Prepare Environment') {
            steps {
                sh 'echo "Preparing environment..."'
            }
        }
        
        
        stage('Connect SSH to EC2') {
            steps {
                sh 'echo "Deploying to EC2 instance..."'                
                // use Jenkins credentials to securely handle SSH keys
                withCredentials([sshUserPrivateKey(credentialsId: 'ec2-user', keyFileVariable: 'SSH_KEY')]) {
                    // Use the SSH key to connect to the EC2 instance and run the deployment script
                    // -o StrictHostKeyChecking=no
                    sh """
                    ssh -i $SSH_KEY ec2-user@ec2-51-92-5-248.eu-south-2.compute.amazonaws.com << EOF
                    cd /home/ec2-user
                    ./hola.sh
                    exit
                    EOF
                    """
                                        
                }
                
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'echo "Building Docker image..."'
                // Build the Docker image
                sh """
                ls
                cd dockerBuild
                docker build -t my-docker-image:latest .
                #docker tag my-docker-image:latest 123456789012.dkr.ecr.eu-south-2.amazonaws.com/my-docker-image:latest
                #docker login --username AWS --password $(aws ecr get-login-password --region eu-south-2) 123456789012.dkr.ecr.eu-south-2.amazonaws.com
                #docker push 123456789012.dkr.ecr.eu-south-2.amazonaws.com/my-docker-image:latest

                """
            }
        }
        stage('Push Docker Image') {
            steps {
                sh 'echo "Pushing Docker image to registry..."'
                 
            }
        }

    
    }

}