// Jenkinsfile
pipeline {
    agent any

    stages {
        stage('Prepare Environment') {
            steps {
                sh 'echo "Preparing environment..."'
            }
        }
        
        
        stage('Deploy to EC2') {
            steps {
                sh 'echo "Deploying to EC2 instance..."'                
                // use Jenkins credentials to securely handle SSH keys
                withCredentials([sshUserPrivateKey(credentialsId: 'ec2-user', keyFileVariable: 'SSH_KEY')]) {
                    // Use the SSH key to connect to the EC2 instance and run the deployment script
                    // -o StrictHostKeyChecking=no
                    sh """
                    ssh -i $SSH_KEY ec2-user@ec2-51-92-5-248.eu-south-2.compute.amazonaws.com << EOF
                    cd /home/ec2-user
                    ./hola.sh
                    exit
                    EOF
                    """
                                        
                }
                
            }
        }

    
    }

}