// Jenkinsfile
pipeline {
    agent {
        label 'jenkins-agent-docker'
    }

    stages {
        stage('Prepare Environment') {
            steps {
                sh 'echo "Preparing environment..."'
            }
        }
     

        stage('Build Docker Image') {
            steps {
                sh 'echo "Building Docker image..."'
                // Build the Docker image
                sh """
                ls
                cd dockerBuild
                docker build -t my-docker-image:latest .                
                """
            }
        }
        stage('Push Docker Image') {
            steps {
                sh 'echo "Pushing Docker image to registry..."'
                 
            }
        }

    
    }

}